trigger:
  branches:
    include:
    - master
  paths:
    include:
    - docker/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: azure-variables.yml
- group: JMETER_TERRAFORM_SETTINGS

stages:
  - stage: BuildPush
    displayName: 'Build and Push JMeter Docker image'
    jobs:
    - job:
      steps:
        - task: AzureKeyVault@1
          inputs:
            azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
            KeyVaultName: $(KEY_VAULT_NAME)
            SecretsFilter: 'acr-secret,arm-client-secret'
          displayName: 'Get secrets from Azure Key Vault'

        - task: AzureCLI@2
          displayName: 'ACR login'
          inputs:
            azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr login -n $(TF_VAR_JMETER_IMAGE_REGISTRY_NAME) -u $(TF_VAR_JMETER_IMAGE_REGISTRY_USERNAME) -p $(acr-secret)
              
        - task: AzureCLI@2
          displayName: 'Build and Push JMeter Docker image'
          inputs:
            azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr build -t $(TF_VAR_JMETER_DOCKER_IMAGE) -r $(TF_VAR_JMETER_IMAGE_REGISTRY_NAME) -f $(Build.SourcesDirectory)/docker/Dockerfile $(Build.SourcesDirectory)/docker
