trigger:
  branches:
    include:
    - main
  paths:
    include:
    - docker/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: JMETER_TERRAFORM_SETTINGS

steps:

- task: AzureCLI@2
  displayName: 'Build and Push JMeter Docker image'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr build -t $(TF_VAR_JMETER_DOCKER_IMAGE) -r $(TF_VAR_JMETER_ACR_NAME) -f $(Build.SourcesDirectory)/docker/Dockerfile $(Build.SourcesDirectory)/docker
